locals {
  aws_region                           = "us-east-1"
  account_id                           = "311923415472"
  repository                           = "wearecircleup/wearecircleup-infra"
  github_actions_role                  = "arn:aws:iam::311923415472:role/GitHubActionsDeployRole"
  state_bucket_name                    = "wearecircleup-terraform-state-311923415472-us-east-1"
  validation_bucket_name               = "wearecircleup-terraform-check-311923415472-us-east-1"
  eventbrite_secret_name               = "wearecircleup/prod/eventbrite"
  ses_domain                           = "circleup.com.co"
  eventbrite_api_name                  = "wearecircleup-prod-eventbrite-api"
  eventbrite_api_lambda                = "wearecircleup-prod-eventbrite-api"
  eventbrite_api_role                  = "wearecircleup-prod-eventbrite-api-role"
  eventbrite_order_webhook_api         = "wearecircleup-prod-eventbrite-order-webhook"
  eventbrite_order_webhook_lambda      = "wearecircleup-prod-eventbrite-order-webhook"
  eventbrite_order_webhook_role        = "wearecircleup-prod-eventbrite-order-webhook-role"
  eventbrite_order_webhook_path        = "/webhooks/eventbrite/order-place"
  eventbrite_order_webhook_table       = "wearecircleup-prod-eventbrite-order-submissions"
  minor_authorization_jobs_table       = "wearecircleup-prod-minor-authorization-jobs"
  minor_authorization_reminder_lambda  = "wearecircleup-prod-minor-authorization-reminder"
  minor_authorization_reminder_role    = "wearecircleup-prod-minor-authorization-reminder-role"
  minor_authorization_reminder_rule    = "wearecircleup-prod-minor-authorization-reminder-daily"
  minor_authorization_reminder_sender  = "hola@circleup.com.co"
  minor_authorization_reminder_form    = "https://app.youform.com/forms/iamr7tnj"
  minor_authorization_validator_lambda = "wearecircleup-prod-minor-authorization-validator"
  minor_authorization_validator_role   = "wearecircleup-prod-minor-authorization-validator-role"
  minor_authorization_validation_queue = "wearecircleup-prod-minor-authorization-validation"
  minor_authorization_validation_dlq   = "wearecircleup-prod-minor-authorization-validation-dlq"
  youform_webhook_api                  = "wearecircleup-prod-youform-webhook"
  youform_webhook_lambda               = "wearecircleup-prod-youform-webhook"
  youform_webhook_role                 = "wearecircleup-prod-youform-webhook-role"
  youform_webhook_path                 = "/webhooks/youform"
  youform_webhook_table                = "wearecircleup-prod-youform-submissions"
  youform_signatures_bucket            = "wearecircleup-prod-youform-signatures-311923415472-us-east-1"

  common_tags = {
    ManagedBy   = "terraform"
    Environment = "prod"
    Project     = "wearecircleup"
    Repository  = local.repository
  }
}
